// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("LemonadeSpliceProvider.DesignTime")>]
[<assembly: AssemblyProductAttribute("LemonadeSpliceProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing LemonadeSpliceProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "LemonadeSpliceProvider.DesignTime"
    let [<Literal>] AssemblyProduct = "LemonadeSpliceProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing LemonadeSpliceProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
